Web/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Web.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Web/Pages/Index.cshtml.cs
using SimpleTodoList.Service;
using SimpleTodoList.MutableCore;
using System;
using System.Collections.Generic;
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;

namespace Web.Pages {

    public class IndexModel : PageModel {

        private ITodoListService _service;

        [BindProperty]
        public IEnumerable<(string name, string description, bool complete, DateTime lastEventDate, string lastEventType)> 
                Items { get; private set; }

        public string UserName { get; set; }
        
        [TempData]
        public string DisplayMessage { get; set; }

        public IndexModel(ITodoListService service, IHttpContextAccessor httpContextAccessor){
            _service = service;        
            UserName =  httpContextAccessor.HttpContext.User.Identity.IsAuthenticated ? 
                httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.Name).Value :
                "Unregistered User";
        }

        public IActionResult OnGet(){
            
            try {
                Items = _service.GetListItems(UserName);
            } catch (TodoListNotFoundException){
                _service.CreateList(UserName);
                Items = _service.GetListItems(UserName);
                DisplayMessage = $"Created new list for user {UserName}";
            }
            return Page();
        }

        public IActionResult OnPostCreate(string name, string description){

            try { 
                _service.AddItem(UserName, name, description);
                DisplayMessage = $"Added Todo Item: {name}";
            } catch (Exception ex) when (
                    ex is TodoItemAlreadyExistsException || 
                    ex is ArgumentNullException) {
                DisplayMessage = ex.Message;
            }

            return RedirectToPage();
        }

        public IActionResult OnPostEdit(string id, string name, string description){
            
            try {
                if (id != name)
                    _service.ChangeItemName(UserName, id, name);
                else 
                    _service.ChangeItemDescription(UserName, id, description);
                DisplayMessage = $"Modified TodoItem {id}";
            }  catch (Exception ex) when (
                    ex is TodoItemAlreadyExistsException || 
                    ex is ArgumentNullException) {
                DisplayMessage = ex.Message;
            }
            
            return RedirectToPage();
        }

        public IActionResult OnPostRemove(string id){

            _service.RemoveItem(UserName, id);
            return RedirectToPage();
        }

        public IActionResult OnPostComplete(string id){
        
            _service.CompleteItem(UserName, id);
            return RedirectToPage();
        }
    }
}

Web/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = $"{@Model.UserName}'s Todo List";
}

<div class="text-center">
    <h4>@Model.UserName's Todo List</h4>
    <br/>
    @if (!Model.Items.Any()){
        <p class="empty">No Todo items!</p>
    } 
    else {
        @foreach (var item in Model.Items) {
        <div class="row">
            <div class="col">
            <form method="post" asp-page="Index" asp-page-handler="Edit" style="display: inline" class="form-inline">
                <input type="hidden" name="id" value="@item.name" />
                <input type="text" name="name" class="form-control" value="@item.name"/>
                <input type="text" name="description" class="form-control" value="@item.description "/>
                 @if (@item.complete){
                     <span class="far fa-check-square fa-lg"></span>
                 }
                 else {
                     <span class="far fa-square fa-lg"></span>
                 }
                <input class="form-control" readonly type="text" value="@item.lastEventType (@item.lastEventDate)" />
                <button type="submit" class="btn btn-primary">Edit</button>
            </form>
            <form method="post" asp-page="Index" asp-page-handler="Remove" style="display: inline">
                <input type="hidden" name="id" value="@item.name" />
                <button type="submit" name="name" class="btn btn-primary" style="background-color:red">Delete</button>
            </form>
            <form method="post" asp-page="Index" asp-page-handler="Complete" style="display: inline">
                <input type="hidden" name="id" value="@item.name" />
                <button type="submit" name="name" class="btn btn-primary" style="background-color:green">Complete</button>
            </form>
            </div>
        </div>
        }
    }
    
    <p class="text-success">@Model.DisplayMessage</p>
    <form asp-page="Index" asp-page-handler="Create" method="post" class="form-inline" style="display: inline">
        <input type="text" name="name" class="form-control" placeholder="Name" />
        <input type="text" name="description" class="form-control" placeholder="Description" />
        <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span>Add</button>
    </form>
 </div>   

Web/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SimpleTodoList</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://kit.fontawesome.com/dd14df2e78.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">SimpleTodoList</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - SimpleTodoList
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>